### ISSUE TITLE
changes to file do not get recognized

### ISSUE THREAD

**Issue by nicolasfromme** [Crunchyman-ralph/shopify-app-node-monorepo-express-vite#24]
Changes made to a component do not get recognized. The app still shows the old code from before the change. Re-running yarn dev and closing the IDE have no effect.

**Comment by Crunchyman-ralph** [comment]
2 options:

- 1: 
  - delete the `node_modules` folder inside `web/frontend/node_modules`
- 2:
  - run `yarn gen:tsconfig`
